### PR TITLE
Wallaby.js configuration

### PR DESCRIPTION
**Pull request by ArtemGovorov**

### CODE REVIEW

**Comment by markogresak** [comment]
Thanks for this! 
I'm not sure what I'm doing wrong at this point, but when I try to run wallaby with this new config from atom, I now get this error `Postprocessor run failure: Could not find file: '~/.atom/packages/atom-wallaby/projects/d44a2b1bb4ae6987/instrumented/src/actions/HomeActions.tsx'.`

**Comment by ArtemGovorov** [comment]
It looks like your wallaby core still hasn't been updated. Could you please check wallaby Core version? Should be v1.0.101 (you may see the version in DevTools `Cmd + Alt + I`). It updates automatically, but may take a few minutes between update checks.

**Comment by markogresak** [comment]
I've missed that part somehow, sorry. Funny, it updated the same moment as the mail from github about your post arrived :smile: 
It's at the correct version now and it's working great and it's so awesome! Thanks again :+1:

**Comment by ArtemGovorov** [comment]
Heh, awesome, good timing. :)

**Pull request merged**
